version: "3.8"
services:
  outbox_transformer:
    container_name: outbox_transformer
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    networks:
      - kafka
    depends_on:
      - outbox_db
    env_file:
      - .env
    volumes:
      - ./transformer.log:/transformer.log
      - ./transformer_errors.log:/transformer_errors.log
      - ./publication_data.log:/publication_data.log
  outbox_db:
    image: postgres:11.8
    container_name: "outbox_database"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - "54323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/postgres/local_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - outbox_transformer
      - kafka
  outbox_transformer_connector:
    build:
      context: ./deploy/kafka/sink_connector
      dockerfile: ./Dockerfile
    container_name: message-relay-connector
    ports:
      - "8084:8083"
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=broker_a:9092,broker_b:9092,broker_c:9092
      - CONNECT_GROUP_ID=debezium_outbox_transformer
      - CONNECT_CONFIG_STORAGE_TOPIC=outbox-transformer-connector-configs
      - CONNECT_OFFSET_STORAGE_TOPIC=outbox-transformer-connector-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=outbox-transformer-connector-status
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
      - CONNECT_PLUGIN_PATH=/usr/local/share/kafka/plugins
    networks:
      - kafka
    volumes:
      - logs:/kafka/logs
      - config:/kafka/config
  debezium-ui:
    image: debezium/debezium-ui
    ports:
      - 8085:8080
    environment:
      - KAFKA_CONNECT_URIS=http://message-relay-connector:8083
    depends_on:
      - outbox_transformer_connector
    networks:
      - kafka

networks:
  kafka:
    external: true
    name: kafka
  outbox_transformer:
    name: outbox_transformer

volumes:
  postgres_data:
  logs:
  config:
